name: Build and Test
on:
  push:
    branches:
      - "main"    # future-proof
      - "master"  # naming
  workflow_dispatch:
jobs:
  start-test-runner:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        # All three major OS types are supported
        os: [windows-latest, macos-latest, ubuntu-latest]
        # RingoJS supports all current LTS releases:
        java: ["8", "11", "17"]
    name: ${{ matrix.os }} - JDK ${{ matrix.java }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: "temurin"
        java-version: ${{ matrix.java }}
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Execute build and run all tests
      run: ./gradlew build
